### PR TITLE
Small page/manual link fixes

### PR DESCRIPTION
**Pull request by TymonKilich**
Hi, I've decided to try to do something useful as I was going through manual 😃 

I fixed the links in the readme and at the index page of the manual (they didn't work). I also changed links from `juliasymbolics.github.io/SymbolicUtils.jl` to `https://symbolicutils.juliasymbolics.org`. Not sure whether it's the right way. I see the pages are in `PkgPage.jl` and it said to edit index.md directly.

I think it will be easier for first time contributors (such as me) if it was written what are the docs/pages built in. It says "Website built with Franklin.jl." at the bottom of the page, but I've found that PkgPage.jl is used only after looking at CI and gh-pages branch. So I added PkgPage.jl with link to "Website built with..." part in the footer.

### CODE REVIEW

**Comment by TymonKilich** [comment]
WIP: I've found some more issues with the pages/manual. 

- [ ] The first example in [Rule based rewriting section](https://symbolicutils.juliasymbolics.org/rewrite/#rule-based_rewriting)

Please treat this PR as WIP.

**Comment by shashi** [comment]
Thanks, these are awesome fixes!

Those broken examples are  a bit of a good problem :-p the simplifications happen automatically. But we should fix it! It's my bad for not keeping an eye on them.

**Comment by TymonKilich** [comment]
I can try to fix the examples and come up with the new ones if that's okay with you. :)

If yes should this be a part of this PR or should I create a new one and limit this one to just fixes of the links?

**Comment by shashi** [comment]
Of course, thank you!! In this PR is fine!

**Comment by MasonProtter** [comment]
Maybe we should just merge this one in the meantime and open a new PR for the example so these problems get fixed ASAP.

**Comment by TymonKilich** [comment]
Sure, by all means merge as it is. Fixing manual takes a bit more time than I thought and I'll do it in separate PR.

I have no idea why the test fail. I didn't touch anything related to tests.

**Review by MasonProtter — APPROVED** [review]

**Comment by TymonKilich** [comment]
> Maybe we should just merge this one in the meantime and open a new PR for the example so these problems get fixed ASAP.

I've almost fixed listed problems. I nearly finished Getting Started and Term Rewriting sections. Only two things left.
Can't really come up with good example for `@acrule` since now it simplifies by default and I'd like to have some nicer example for Composing rewriters.

I'll open a PR tomorrow (actually later today where I live). Haven't looked into Interfacing, Code generation and API Reference sections yet but they may be left for further PR if you prefer to fix examples ASAP.

**Comment by ChrisRackauckas** [comment]
Those downstream issues were some versioning things we fixed over the last day.

**Pull request merged**
