### PR TITLE
Extensible trait-like dispatch for Number methods

### PR DESCRIPTION
**Pull request by shashi**
Solves #134 

cc @YingboMa what do you think?

### CODE REVIEW

**Comment by shashi** [comment]
@david-pl You'd have to define `islike(::Symbolic{<:QNumber}, ::Type{Number}) = true` now.

**Comment by AshtonSBradley** [comment]
is there any relation between this and Complex number support for ModelingToolkit?

**Comment by shashi** [comment]
Not right now, but potentially!

**Comment by ChrisRackauckas** [comment]
It's definitely moving along in the right direction.

**Pull request merged**
