### PR TITLE
adjoint(y::Symbolic{<:Number})

### PR DESCRIPTION
**Pull request by ChristophHotter**
I added the method  `adjoint(y::Symbolic{<:Number}) = conj(s)`. 
This is what Julia does for example with `adjoint(1im)`.

### CODE REVIEW

**Review by bowenszhu — CHANGES_REQUESTED** [review]
Thanks for the PR! Could you add some test?

**Comment by ChristophHotter** [comment]
Yes, I added tests for Real and Complex syms.

**Review by bowenszhu — CHANGES_REQUESTED** [review]
[`Base.adjoint`](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Base.adjoint) implements lazy evaluation.
https://github.com/JuliaLang/julia/blob/6f3fdf7b36250fb95f512a2b927ad2518c07d2b5/stdlib/LinearAlgebra/src/adjtrans.jl#L280

```julia
A = [3+2im 9+2im; 0  0]
adjoint(adjoint(A)) === A
```
`adjoint` of an `adjoint` is the original variable. 
We should mimic the same behavior.

**Review by bowenszhu — APPROVED** [review]
Looks good. Thank you!

https://github.com/JuliaLang/julia/blob/6f3fdf7b36250fb95f512a2b927ad2518c07d2b5/base/number.jl#L225

**Comment by ChristophHotter** [comment]
Thanks!

**Pull request merged**
