### PR TITLE
Make metadata a keyword

### PR DESCRIPTION
**Pull request by YingboMa**
Positional arguments are used for indices in Symbolics.jl

### CODE REVIEW

**Comment by shashi** [comment]
Oops, okay this needs some fixes.

**Comment by shashi** [comment]
The reverse CI didn't catch this :roll_eyes:

**Comment by ChrisRackauckas** [comment]
You know what that means. https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/220

**Comment by shashi** [comment]
then we gotta remove this https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/master/test/runtests.jl#L25-L30

**Comment by shashi** [comment]
DDDiffEq fails with "WARNING: both ModelingToolkit and DataDrivenDiffEq export "jacobian"; uses of it in module Main must be qualified" unrelated but just pointing it out.

**Pull request merged**
