### PR TITLE
Split Rewriters module into different package

### PR DESCRIPTION
**Pull request by 0x0f0f0f**

### CODE REVIEW

**Comment by 0x0f0f0f** [comment]
Tests will pass when Rewriters.jl is registered. See 
https://github.com/JuliaRegistries/General/pull/44045

**Comment by shashi** [comment]
Need to update the docs to make it clear how to get the rewriters. Maybe just say you will need to add the Rewriters package and do `using Rewriters` then later we can point to a Rewriters.jl documentation if that exists.

**Comment by shashi** [comment]
what's up with the repo name? https://github.com/JuliaSymbolics/RewriterCombinators.jl ?

**Comment by 0x0f0f0f** [comment]
Anything missing to merge this PR?

**Comment by 0x0f0f0f** [comment]
Merged latest master

**Comment by 0x0f0f0f** [comment]
All green!!

**Comment by 0x0f0f0f** [comment]
Temporarily closing because of https://discourse.julialang.org/t/a-recap-of-the-state-of-the-symbolics-ecosystem/68022

**Pull request closed without merging**
