### PR TITLE
propagate constants after substitute

### PR DESCRIPTION
**Pull request by shashi**

### CODE REVIEW

**Comment by YingboMa** [comment]
Looks like this PR got some commits from `s/hastrig`

**Comment by shashi** [comment]
https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/100/commits/cee85f6c02dac142b1e46ec0499dc41be2ea3c66 this should test it.

**Comment by YingboMa** [comment]
Cool! Do you want to make a new release? LGTM

**Comment by shashi** [comment]
let me remove the other commits haha

**Comment by shashi** [comment]
closes #30 also.

**Pull request merged**
