### PR TITLE
Fix documentation build

### PR DESCRIPTION
**Pull request by shashi**

### CODE REVIEW

**Comment by YingboMa** [comment]
Good to merge?

**Comment by ArnoStrouwen** [comment]
Don't merge this, since we added Documenter. If you add both, they will start overwriting each other.

**Comment by shashi** [comment]
You need to help get #508 published.

**Comment by ArnoStrouwen** [comment]
https://symbolicutils.juliasymbolics.org/dev/

> But where is the documenter output ?

**Pull request closed without merging**
