### PR TITLE
Fix `rec_promote_symtype` so that it only recurse on VARARGFUNS

### LINKED ISSUE #167: Breaking changes in 0.7.4
Hi,

Using SymbolicUtils 0.7.3 in the `dev` branch of Soss, I can set up this model:
```julia
using Soss, MeasureTheory

m = @model σ begin
    μ ~ StudentT(3.0)
    x ~ Laplace(μ, σ) |> iid(1000)
    return x
end;
```

And then this works just fine:
```julia
julia> symlogdensity(m(σ=2.0))
3.4166191036395746 + -2.0log(3.0 + (μ^2)) + -1(693.1471805599452 + Sum(abs(-0.5μ + 0.5getindex(x, ##i#270)), ##i#270, 1, 1000))
```

But in 0.7.4 I get an error. The source of it seems to be changes in `simplify`. First, setting it up:
```julia
julia> sourceSymlogdensity(m(σ=2.0))
quote
    _ℓ = 0.0
    σ = Soss.Sym{Float64}(:σ)
    μ = Soss.Sym{Float64}(:μ)
    _ℓ += logdensity(StudentT(3.0), μ)
    x = Soss.Sym{Vector{Float64}}(:x)
    _ℓ += logdensity(Laplace(μ, σ) |> iid(1000), x)
    nothing
    return _ℓ
end

julia> _ℓ
3.4166191036395746 + -2.0log(3.0 + (μ^2)) + Sum(-1log(σ) + -1abs((σ^-1)*(getindex(x, ##i1#250) + -1μ)), ##i1#250, 1, 1000)
```

Then `simplify` breaks:
```julia
julia> simplify(_ℓ)
ERROR: Sum(::Number, ::Int64, ::Int64, ::Int64)::Number takes 4 arguments; 2 arguments given
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/hUjlV/src/types.jl:182
  [3] rec_promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Vararg{Type, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/hUjlV/src/methods.jl:107
  [4] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, ::Vararg{Any, N} where N; type::Nothing)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/hUjlV/src/types.jl:302
  [5] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, ::Vararg{Any, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/hUjlV/src/types.jl:301
  [6] similarterm
    @ ~/.julia/packages/SymbolicUtils/hUjlV/src/types.jl:316 [inlined]
  [7] (::SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false})(x::SymbolicUtils.Term{Number})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:139
  [8] (::SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}})(x::SymbolicUtils.Term{Number})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:129
  [9] iterate
    @ ./generator.jl:47 [inlined]
 [10] collect_to!(dest::Vector{Any}, itr::Base.Generator{Vector{Any}, SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}}, offs::Int64, st::Int64)
    @ Base ./array.jl:724
 [11] collect_to!(dest::Vector{Float64}, itr::Base.Generator{Vector{Any}, SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}}, offs::Int64, st::Int64)
    @ Base ./array.jl:732
 [12] collect_to_with_first!(dest::Vector{Float64}, v1::Float64, itr::Base.Generator{Vector{Any}, SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}}, st::Int64)
    @ Base ./array.jl:702
 [13] _collect(c::Vector{Any}, itr::Base.Generator{Vector{Any}, SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
    @ Base ./array.jl:696
 [14] collect_similar
    @ ./array.jl:606 [inlined]
 [15] map(f::SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}, A::Vector{Any})
    @ Base ./abstractarray.jl:2281
 [16] (::SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false})(x::SymbolicUtils.Add{Number, Float64, Dict{Any, Number}})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:139
 [17] IfElse
    @ ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:48 [inlined]
 [18] (::SymbolicUtils.Rewriters.Fixpoint{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#164#237", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#165#238", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(SymbolicUtils.similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}})(x::SymbolicUtils.Add{Number, Float64, Dict{Any, Number}})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:101
 [19] IfElse
    @ ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:48 [inlined]
 [20] (::SymbolicUtils.Rewriters.PassThrough{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.istree), SymbolicUtils.Rewriters.Fixpoint{SymbolicUtils.Rewriters.IfElse{typeof(SymbolicUtils.has_trig), SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#164#237", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.IfElse{SymbolicUtils.var"#165#238", SymbolicUtils.Rewriters.Chain, SymbolicUtils.Rewriters.Empty}}, typeof(SymbolicUtils.similarterm), false}, SymbolicUtils.Rewriters.Walk{:post, SymbolicUtils.Rewriters.Chain, typeof(SymbolicUtils.similarterm), false}}}, SymbolicUtils.Rewriters.Empty}})(x::SymbolicUtils.Add{Number, Float64, Dict{Any, Number}})
    @ SymbolicUtils.Rewriters ~/.julia/packages/SymbolicUtils/hUjlV/src/rewriters.jl:129
 [21] simplify(x::SymbolicUtils.Add{Number, Float64, Dict{Any, Number}}; polynorm::Bool, threaded::Bool, thread_subtree_cutoff::Int64, rewriter::Nothing)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/hUjlV/src/api.jl:29
 [22] simplify(x::SymbolicUtils.Add{Number, Float64, Dict{Any, Number}})
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/hUjlV/src/api.jl:17
 [23] top-level scope
    @ REPL[17]:1
 [24] eval
    @ ./boot.jl:360 [inlined]
```

I can't imagine why it would be trying to rewrite my `Sum` terms. Any ideas?

More generally, is there a way I should be doing things to be sure patch releases don't break things?

### PR DESCRIPTION
**Pull request by YingboMa**
Fix #167

### CODE REVIEW

**Comment by cscherrer** [comment]
Oh hmm, not quite there yet:
```julia
julia> symlogdensity(m(σ=2.0))
ERROR: Argument to Sum(::Number, ::Int64, ::Int64, ::Int64)::Number at position 1 must be of symbolic type Number
```

**Comment by cscherrer** [comment]
```julia
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Vararg{Type, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/E5B17/src/types.jl:188
  [3] rec_promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Type)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/E5B17/src/methods.jl:108
  [4] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, ::Vararg{Any, N} where N; type::Nothing)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/E5B17/src/types.jl:302
  [5] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, ::Vararg{Any, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/E5B17/src/types.jl:301
  [6] similarterm
    @ ~/.julia/packages/SymbolicUtils/E5B17/src/types.jl:316 [inlined]
```

**Comment by YingboMa** [comment]
@cscherrer could you try again?

**Comment by cscherrer** [comment]
Ok it's running now.

Wait waiting, I wonder if this is from the way I'm doing substitution. I've found it helpful to have a type
```julia
const MaybeSym{T} = Union{T, Symbolic{T}}
```

Maybe something like this could be useful in SymbolicUtils?

**Comment by cscherrer** [comment]
Update: yep it still breaks. I'm guessing the substitution is breaking it

**Comment by cscherrer** [comment]
wait maybe not
```julia
julia> s
3.4166191036395746 + Sum(-1log(σ) + -1abs((σ^-1)*(getindex(x, ##i1#250) + -1μ)), ##i1#250, 1, 1000) + -2.0log(3.0 + (μ^2))

julia> simplify(s)
ERROR: Argument to Sum(::Number, ::Int64, ::Int64, ::Int64)::Number at position 1 must be of symbolic type Number
Stacktrace:
  [1] error(s::String)
    @ Base ./error.jl:33
  [2] promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Vararg{Type, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/EkeHW/src/types.jl:188
  [3] rec_promote_symtype(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::Type, ::Type, ::Type, ::Vararg{Type, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/EkeHW/src/methods.jl:110
  [4] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, ::Vararg{Any, N} where N; type::Nothing)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/EkeHW/src/types.jl:302
  [5] term(::SymbolicUtils.Sym{SymbolicUtils.FnType{Tuple{Number, Int64, Int64, Int64}, Number}}, ::SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, ::Vararg{Any, N} where N)
    @ SymbolicUtils ~/.julia/packages/SymbolicUtils/EkeHW/src/types.jl:301
  [6] similarterm
```

**Comment by YingboMa** [comment]
Could you reduce it a bit with the printing trick?

**Comment by cscherrer** [comment]
sure one sec

**Comment by cscherrer** [comment]
```julia
julia> symlogdensity(m(σ=2.0))
(f, typeof.(args)) = (log, DataType[SymbolicUtils.Add{Float64, Float64, Dict{Any, Number}}])
(f, typeof.(args)) = (log, DataType[SymbolicUtils.Sym{Float64}])
(f, typeof.(args)) = (getindex, DataType[SymbolicUtils.Sym{Vector{Float64}}, SymbolicUtils.Sym{Int64}])
(f, typeof.(args)) = (abs, DataType[SymbolicUtils.Mul{Any, Int64, Dict{Any, Number}}])
(f, typeof.(args)) = (Sum(::Number, ::Int64, ::Int64, ::Int64)::Number, DataType[SymbolicUtils.Add{Any, Int64, Dict{Any, Number}}, SymbolicUtils.Sym{Int64}, Int64, Int64])
ERROR: Argument to Sum(::Number, ::Int64, ::Int64, ::Int64)::Number at position 1 must be of symbolic type Number
```

**Comment by cscherrer** [comment]
Here's the term that throws it off:
```julia
julia> arguments(s)[3] 
Sum(-1log(σ) + -1abs((σ^-1)*(getindex(x, ##i1#250) + -1μ)), ##i1#250, 1, 1000)

julia> arguments(s)[3] |> arguments
4-element Vector{Any}:
     -1log(σ) + -1abs((σ^-1)*(getindex(x, ##i1#250) + -1μ))
     ##i1#250
    1
 1000

julia> ans[1] |> typeof
SymbolicUtils.Add{Real, Int64, Dict{Any, Number}}
```

I think its type is ok, I guess `simplify` pulls it apart and puts it back together differently?

**Comment by cscherrer** [comment]
Oh this is weird @YingboMa. Just before the error I get 
```julia
args[i] = Any
typeof(args[i]) = DataType
```

**Comment by shashi** [comment]
#169 works for me with your test case @cscherrer

**Pull request closed without merging**
