### PR TITLE
Extend and document canonical form of `Symbolic{<:Number}`

### LINKED ISSUE #256: Document canonical form of Number terms
We have an informal "canonical" form for Terms of symtype Number right now. But we don't have a good succinct definition of the same.

For example `1 * x` always returns `x`. `x * x` always returns `x^2` and so on.

Having a definition of this will help us speed up things like `isequal` and have it be more accurate.

### PR DESCRIPTION
**Pull request by Suavesito-Olimpiada**
fix #256

### CODE REVIEW

**Comment by Suavesito-Olimpiada** [comment]
As I saw when writing this docs, there are things that can be done to further improve the canonical form just using `Mul`, `Add` and `Pow`. Some of these are "fussing" expressions of type `Pow` and `Mul`.

I can contribute these this week, but I don't know if put them in this PR or make another with "just the code". If is needed in another PR i would extend the docs here to reflect the changes made in the other PR.

I also don't know if I should add here in the docs the optimizations for some functions (as in [262](https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/262)) or not, and all the "basic" operators `[+, -, \, /, ^, *]`.

**Comment by shashi** [comment]
> Some of these are "fussing" expressions of type Pow and Mul.

What do you mean by this?

What are the changes you're planning to make? Feel free to put them in this PR! :)

**Comment by Suavesito-Olimpiada** [comment]
> > Some of these are "fusing" expressions of type Pow and Mul.
> 
> What do you mean by this?

In master now you have that

```julia
julia> x*inv(x)
1
```

For some `x` expressions, but

```julia
julia> (x^-1)*inv(x^-1)
(x^-1)*((x^-1)^-1)
```

And you can see why this is happening

```julia
julia> print_tree((x^-1)*inv(x^-1))
*
├─ 1
├─ (^)
│  ├─ x
│  └─ -1
└─ (^)
   ├─ ^
   │  ├─ x
   │  └─ -1
   └─ -1
```

Basically `Mul` is not merging (what I called "fusing") with `Pow`.

**Comment by Suavesito-Olimpiada** [comment]
I found what it is happening, the `Mul` *does merge with `Pow`, but `Pow` doesn't reduce with another `Pow`.

**Comment by Suavesito-Olimpiada** [comment]
Now with this PR, aside the documentation

```julia
julia> (x^-1)*inv(x^-1)
1
```

Still needs to finish the documentation part.

**Comment by YingboMa** [comment]
Could you add a test for `(x^-1)*inv(x^-1)` in here https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/491ad806c8a21b75c11efd930fbce7af0de1fcfe/test/basics.jl#L187

**Comment by Suavesito-Olimpiada** [comment]
Yeah, sure. I finished adding the documentation. And I added the test.

**Comment by Suavesito-Olimpiada** [comment]
Locally all the test passed :smile:, now to the next issue. :stuck_out_tongue:

**Pull request merged**
