### PR TITLE
Add upgrade guide

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by YingboMa** [comment]
It doesn't seem like the guide is up in https://symbolicutils.juliasymbolics.org/ . @shashi could you help me set it up?

**Comment by shashi** [comment]
It's because this PR deleted my build script and didn't actually publish the documenter lol https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/488 @ArnoStrouwen

**Comment by YingboMa** [comment]
Could we fix that? :p

**Comment by shashi** [comment]
I don't think copy-pasting works either, the syntax of Documenter and my repl syntax are different. I'm going to put the deploy script back, and let @ArnoStrouwen figure out Documenter later.

**Pull request merged**
